server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     /etc/nginx/cert.pem;
    ssl_certificate_key /etc/nginx/key.pem;

    location = /shibauthorizer {
        internal;
        include shib_fastcgi_params;
        fastcgi_pass unix:/run/shibboleth/shibauthorizer.sock;
    }

    location /Shibboleth.sso {
        include shib_fastcgi_params;
        fastcgi_pass unix:/run/shibboleth/shibresponder.sock;
    }

    location /shibboleth-sp {
        alias /usr/share/shibboleth/;
    }

    location /secure {
        include shib_clear_headers;
        shib_request /shibauthorizer;
        shib_request_use_headers on;

        root /usr/share/nginx/html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}
